version: '3.8'
services:
  router1_host1:
    build: ./host
    container_name: router1_host1
    networks:
      router1_host1_net:
        ipv4_address: 192.168.1.2
  router1_host2:
    build: ./host
    container_name: router1_host2
    networks:
      router1_host2_net:
        ipv4_address: 192.168.2.2
  router1:
    build: ./router
    container_name: router1
    environment:
      CONTAINER_NAME: router1
    volumes:
    - ./router/router.py:/app/router.py
    cap_add:
    - NET_ADMIN
    networks:
      router1_host1_net:
        ipv4_address: 192.168.1.10
      router1_host2_net:
        ipv4_address: 192.168.2.10
      router1_router11_net:
        ipv4_address: 10.10.1.10
  router2_host1:
    build: ./host
    container_name: router2_host1
    networks:
      router2_host1_net:
        ipv4_address: 192.168.3.2
  router2_host2:
    build: ./host
    container_name: router2_host2
    networks:
      router2_host2_net:
        ipv4_address: 192.168.4.2
  router2:
    build: ./router
    container_name: router2
    environment:
      CONTAINER_NAME: router2
    volumes:
    - ./router/router.py:/app/router.py
    cap_add:
    - NET_ADMIN
    networks:
      router2_host1_net:
        ipv4_address: 192.168.3.10
      router2_host2_net:
        ipv4_address: 192.168.4.10
      router2_router3_net:
        ipv4_address: 10.10.2.10
      router2_router5_net:
        ipv4_address: 10.10.3.10
      router2_router7_net:
        ipv4_address: 10.10.4.10
  router3_host1:
    build: ./host
    container_name: router3_host1
    networks:
      router3_host1_net:
        ipv4_address: 192.168.5.2
  router3_host2:
    build: ./host
    container_name: router3_host2
    networks:
      router3_host2_net:
        ipv4_address: 192.168.6.2
  router3:
    build: ./router
    container_name: router3
    environment:
      CONTAINER_NAME: router3
    volumes:
    - ./router/router.py:/app/router.py
    cap_add:
    - NET_ADMIN
    networks:
      router3_host1_net:
        ipv4_address: 192.168.5.10
      router3_host2_net:
        ipv4_address: 192.168.6.10
      router2_router3_net:
        ipv4_address: 10.10.2.2
      router3_router7_net:
        ipv4_address: 10.10.5.10
      router3_router4_net:
        ipv4_address: 10.10.6.10
      router3_router15_net:
        ipv4_address: 10.10.7.10
  router4_host1:
    build: ./host
    container_name: router4_host1
    networks:
      router4_host1_net:
        ipv4_address: 192.168.7.2
  router4_host2:
    build: ./host
    container_name: router4_host2
    networks:
      router4_host2_net:
        ipv4_address: 192.168.8.2
  router4:
    build: ./router
    container_name: router4
    environment:
      CONTAINER_NAME: router4
    volumes:
    - ./router/router.py:/app/router.py
    cap_add:
    - NET_ADMIN
    networks:
      router4_host1_net:
        ipv4_address: 192.168.7.10
      router4_host2_net:
        ipv4_address: 192.168.8.10
      router3_router4_net:
        ipv4_address: 10.10.6.2
      router4_router8_net:
        ipv4_address: 10.10.8.10
      router4_router12_net:
        ipv4_address: 10.10.9.10
  router5_host1:
    build: ./host
    container_name: router5_host1
    networks:
      router5_host1_net:
        ipv4_address: 192.168.9.2
  router5_host2:
    build: ./host
    container_name: router5_host2
    networks:
      router5_host2_net:
        ipv4_address: 192.168.10.2
  router5:
    build: ./router
    container_name: router5
    environment:
      CONTAINER_NAME: router5
    volumes:
    - ./router/router.py:/app/router.py
    cap_add:
    - NET_ADMIN
    networks:
      router5_host1_net:
        ipv4_address: 192.168.9.10
      router5_host2_net:
        ipv4_address: 192.168.10.10
      router2_router5_net:
        ipv4_address: 10.10.3.2
      router5_router6_net:
        ipv4_address: 10.10.10.10
  router6_host1:
    build: ./host
    container_name: router6_host1
    networks:
      router6_host1_net:
        ipv4_address: 192.168.11.2
  router6_host2:
    build: ./host
    container_name: router6_host2
    networks:
      router6_host2_net:
        ipv4_address: 192.168.12.2
  router6:
    build: ./router
    container_name: router6
    environment:
      CONTAINER_NAME: router6
    volumes:
    - ./router/router.py:/app/router.py
    cap_add:
    - NET_ADMIN
    networks:
      router6_host1_net:
        ipv4_address: 192.168.11.10
      router6_host2_net:
        ipv4_address: 192.168.12.10
      router5_router6_net:
        ipv4_address: 10.10.10.2
  router7_host1:
    build: ./host
    container_name: router7_host1
    networks:
      router7_host1_net:
        ipv4_address: 192.168.13.2
  router7_host2:
    build: ./host
    container_name: router7_host2
    networks:
      router7_host2_net:
        ipv4_address: 192.168.14.2
  router7:
    build: ./router
    container_name: router7
    environment:
      CONTAINER_NAME: router7
    volumes:
    - ./router/router.py:/app/router.py
    cap_add:
    - NET_ADMIN
    networks:
      router7_host1_net:
        ipv4_address: 192.168.13.10
      router7_host2_net:
        ipv4_address: 192.168.14.10
      router2_router7_net:
        ipv4_address: 10.10.4.2
      router3_router7_net:
        ipv4_address: 10.10.5.2
  router8_host1:
    build: ./host
    container_name: router8_host1
    networks:
      router8_host1_net:
        ipv4_address: 192.168.15.2
  router8_host2:
    build: ./host
    container_name: router8_host2
    networks:
      router8_host2_net:
        ipv4_address: 192.168.16.2
  router8:
    build: ./router
    container_name: router8
    environment:
      CONTAINER_NAME: router8
    volumes:
    - ./router/router.py:/app/router.py
    cap_add:
    - NET_ADMIN
    networks:
      router8_host1_net:
        ipv4_address: 192.168.15.10
      router8_host2_net:
        ipv4_address: 192.168.16.10
      router4_router8_net:
        ipv4_address: 10.10.8.2
  router9_host1:
    build: ./host
    container_name: router9_host1
    networks:
      router9_host1_net:
        ipv4_address: 192.168.17.2
  router9_host2:
    build: ./host
    container_name: router9_host2
    networks:
      router9_host2_net:
        ipv4_address: 192.168.18.2
  router9:
    build: ./router
    container_name: router9
    environment:
      CONTAINER_NAME: router9
    volumes:
    - ./router/router.py:/app/router.py
    cap_add:
    - NET_ADMIN
    networks:
      router9_host1_net:
        ipv4_address: 192.168.17.10
      router9_host2_net:
        ipv4_address: 192.168.18.10
      router9_router10_net:
        ipv4_address: 10.10.11.10
  router10_host1:
    build: ./host
    container_name: router10_host1
    networks:
      router10_host1_net:
        ipv4_address: 192.168.19.2
  router10_host2:
    build: ./host
    container_name: router10_host2
    networks:
      router10_host2_net:
        ipv4_address: 192.168.20.2
  router10:
    build: ./router
    container_name: router10
    environment:
      CONTAINER_NAME: router10
    volumes:
    - ./router/router.py:/app/router.py
    cap_add:
    - NET_ADMIN
    networks:
      router10_host1_net:
        ipv4_address: 192.168.19.10
      router10_host2_net:
        ipv4_address: 192.168.20.10
      router9_router10_net:
        ipv4_address: 10.10.11.2
      router10_router11_net:
        ipv4_address: 10.10.12.10
  router11_host1:
    build: ./host
    container_name: router11_host1
    networks:
      router11_host1_net:
        ipv4_address: 192.168.21.2
  router11_host2:
    build: ./host
    container_name: router11_host2
    networks:
      router11_host2_net:
        ipv4_address: 192.168.22.2
  router11:
    build: ./router
    container_name: router11
    environment:
      CONTAINER_NAME: router11
    volumes:
    - ./router/router.py:/app/router.py
    cap_add:
    - NET_ADMIN
    networks:
      router11_host1_net:
        ipv4_address: 192.168.21.10
      router11_host2_net:
        ipv4_address: 192.168.22.10
      router1_router11_net:
        ipv4_address: 10.10.1.2
      router10_router11_net:
        ipv4_address: 10.10.12.2
      router11_router12_net:
        ipv4_address: 10.10.13.10
      router11_router13_net:
        ipv4_address: 10.10.14.10
  router12_host1:
    build: ./host
    container_name: router12_host1
    networks:
      router12_host1_net:
        ipv4_address: 192.168.23.2
  router12_host2:
    build: ./host
    container_name: router12_host2
    networks:
      router12_host2_net:
        ipv4_address: 192.168.24.2
  router12:
    build: ./router
    container_name: router12
    environment:
      CONTAINER_NAME: router12
    volumes:
    - ./router/router.py:/app/router.py
    cap_add:
    - NET_ADMIN
    networks:
      router12_host1_net:
        ipv4_address: 192.168.23.10
      router12_host2_net:
        ipv4_address: 192.168.24.10
      router4_router12_net:
        ipv4_address: 10.10.9.2
      router11_router12_net:
        ipv4_address: 10.10.13.2
  router13_host1:
    build: ./host
    container_name: router13_host1
    networks:
      router13_host1_net:
        ipv4_address: 192.168.25.2
  router13_host2:
    build: ./host
    container_name: router13_host2
    networks:
      router13_host2_net:
        ipv4_address: 192.168.26.2
  router13:
    build: ./router
    container_name: router13
    environment:
      CONTAINER_NAME: router13
    volumes:
    - ./router/router.py:/app/router.py
    cap_add:
    - NET_ADMIN
    networks:
      router13_host1_net:
        ipv4_address: 192.168.25.10
      router13_host2_net:
        ipv4_address: 192.168.26.10
      router11_router13_net:
        ipv4_address: 10.10.14.2
  router14_host1:
    build: ./host
    container_name: router14_host1
    networks:
      router14_host1_net:
        ipv4_address: 192.168.27.2
  router14_host2:
    build: ./host
    container_name: router14_host2
    networks:
      router14_host2_net:
        ipv4_address: 192.168.28.2
  router14:
    build: ./router
    container_name: router14
    environment:
      CONTAINER_NAME: router14
    volumes:
    - ./router/router.py:/app/router.py
    cap_add:
    - NET_ADMIN
    networks:
      router14_host1_net:
        ipv4_address: 192.168.27.10
      router14_host2_net:
        ipv4_address: 192.168.28.10
      router14_router15_net:
        ipv4_address: 10.10.15.10
  router15_host1:
    build: ./host
    container_name: router15_host1
    networks:
      router15_host1_net:
        ipv4_address: 192.168.29.2
  router15_host2:
    build: ./host
    container_name: router15_host2
    networks:
      router15_host2_net:
        ipv4_address: 192.168.30.2
  router15:
    build: ./router
    container_name: router15
    environment:
      CONTAINER_NAME: router15
    volumes:
    - ./router/router.py:/app/router.py
    cap_add:
    - NET_ADMIN
    networks:
      router15_host1_net:
        ipv4_address: 192.168.29.10
      router15_host2_net:
        ipv4_address: 192.168.30.10
      router3_router15_net:
        ipv4_address: 10.10.7.2
      router14_router15_net:
        ipv4_address: 10.10.15.2
networks:
  router1_host1_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.1.0/24
  router1_host2_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.2.0/24
  router2_host1_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.3.0/24
  router2_host2_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.4.0/24
  router3_host1_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.5.0/24
  router3_host2_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.6.0/24
  router4_host1_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.7.0/24
  router4_host2_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.8.0/24
  router5_host1_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.9.0/24
  router5_host2_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.10.0/24
  router6_host1_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.11.0/24
  router6_host2_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.12.0/24
  router7_host1_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.13.0/24
  router7_host2_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.14.0/24
  router8_host1_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.15.0/24
  router8_host2_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.16.0/24
  router9_host1_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.17.0/24
  router9_host2_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.18.0/24
  router10_host1_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.19.0/24
  router10_host2_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.20.0/24
  router11_host1_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.21.0/24
  router11_host2_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.22.0/24
  router12_host1_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.23.0/24
  router12_host2_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.24.0/24
  router13_host1_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.25.0/24
  router13_host2_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.26.0/24
  router14_host1_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.27.0/24
  router14_host2_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.28.0/24
  router15_host1_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.29.0/24
  router15_host2_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.30.0/24
  router1_router11_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.10.1.0/24
  router2_router3_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.10.2.0/24
  router2_router5_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.10.3.0/24
  router2_router7_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.10.4.0/24
  router3_router7_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.10.5.0/24
  router3_router4_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.10.6.0/24
  router3_router15_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.10.7.0/24
  router4_router8_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.10.8.0/24
  router4_router12_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.10.9.0/24
  router5_router6_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.10.10.0/24
  router9_router10_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.10.11.0/24
  router10_router11_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.10.12.0/24
  router11_router12_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.10.13.0/24
  router11_router13_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.10.14.0/24
  router14_router15_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.10.15.0/24
