version: '3.8'
services:
  router01_host01:
    build: ./host
    container_name: router01_host01
    networks:
      router01_host01_net:
        ipv4_address: 192.168.1.2
  router01_host02:
    build: ./host
    container_name: router01_host02
    networks:
      router01_host02_net:
        ipv4_address: 192.168.2.2
  router01:
    build: ./router
    container_name: router01
    volumes:
    - ./router/router.py:/app/router.py
    cap_add:
    - NET_ADMIN
    networks:
      router01_host01_net:
        ipv4_address: 192.168.1.10
      router01_host02_net:
        ipv4_address: 192.168.2.10
      router01_router05_net:
        ipv4_address: 10.10.1.10
      router01_router04_net:
        ipv4_address: 10.10.2.10
  router02_host01:
    build: ./host
    container_name: router02_host01
    networks:
      router02_host01_net:
        ipv4_address: 192.168.3.2
  router02_host02:
    build: ./host
    container_name: router02_host02
    networks:
      router02_host02_net:
        ipv4_address: 192.168.4.2
  router02:
    build: ./router
    container_name: router02
    volumes:
    - ./router/router.py:/app/router.py
    cap_add:
    - NET_ADMIN
    networks:
      router02_host01_net:
        ipv4_address: 192.168.3.10
      router02_host02_net:
        ipv4_address: 192.168.4.10
      router02_router05_net:
        ipv4_address: 10.10.3.10
  router03_host01:
    build: ./host
    container_name: router03_host01
    networks:
      router03_host01_net:
        ipv4_address: 192.168.5.2
  router03_host02:
    build: ./host
    container_name: router03_host02
    networks:
      router03_host02_net:
        ipv4_address: 192.168.6.2
  router03:
    build: ./router
    container_name: router03
    volumes:
    - ./router/router.py:/app/router.py
    cap_add:
    - NET_ADMIN
    networks:
      router03_host01_net:
        ipv4_address: 192.168.5.10
      router03_host02_net:
        ipv4_address: 192.168.6.10
      router03_router05_net:
        ipv4_address: 10.10.4.10
  router04_host01:
    build: ./host
    container_name: router04_host01
    networks:
      router04_host01_net:
        ipv4_address: 192.168.7.2
  router04_host02:
    build: ./host
    container_name: router04_host02
    networks:
      router04_host02_net:
        ipv4_address: 192.168.8.2
  router04:
    build: ./router
    container_name: router04
    volumes:
    - ./router/router.py:/app/router.py
    cap_add:
    - NET_ADMIN
    networks:
      router04_host01_net:
        ipv4_address: 192.168.7.10
      router04_host02_net:
        ipv4_address: 192.168.8.10
      router01_router04_net:
        ipv4_address: 10.10.2.2
      router04_router05_net:
        ipv4_address: 10.10.5.10
  router05_host01:
    build: ./host
    container_name: router05_host01
    networks:
      router05_host01_net:
        ipv4_address: 192.168.9.2
  router05_host02:
    build: ./host
    container_name: router05_host02
    networks:
      router05_host02_net:
        ipv4_address: 192.168.10.2
  router05:
    build: ./router
    container_name: router05
    volumes:
    - ./router/router.py:/app/router.py
    cap_add:
    - NET_ADMIN
    networks:
      router05_host01_net:
        ipv4_address: 192.168.9.10
      router05_host02_net:
        ipv4_address: 192.168.10.10
      router01_router05_net:
        ipv4_address: 10.10.1.2
      router02_router05_net:
        ipv4_address: 10.10.3.2
      router03_router05_net:
        ipv4_address: 10.10.4.2
      router04_router05_net:
        ipv4_address: 10.10.5.2
networks:
  router01_host01_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.1.0/24
  router01_host02_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.2.0/24
  router02_host01_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.3.0/24
  router02_host02_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.4.0/24
  router03_host01_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.5.0/24
  router03_host02_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.6.0/24
  router04_host01_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.7.0/24
  router04_host02_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.8.0/24
  router05_host01_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.9.0/24
  router05_host02_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.10.0/24
  router01_router05_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.10.1.0/24
  router01_router04_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.10.2.0/24
  router02_router05_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.10.3.0/24
  router03_router05_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.10.4.0/24
  router04_router05_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.10.5.0/24
