
FROM python:3.10-slim

WORKDIR /app

COPY router.py .
# 3. Copia o arquivo "router.py" do diretório local para o diretório de trabalho no container.

CMD ["python", "router.py"]
# 4. Define o comando padrão para executar o script "router.py" usando o interpretador Python.
